language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  global:
  - RUST_BACKTRACE=1
before_install:
  - set -e
  - rustup self update
script:
  - cargo build --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
  - name: 'cargo fmt check'
    rust: stable
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt -- --check
  - name: 'clippy check'
    rust: stable
    install:
    - rustup component add clippy
    script:
    - cargo clippy -- -D warnings
